### ISSUE TITLE
val_step() in IterBasedRunner, optimizer error.

### ISSUE THREAD

**Issue by alpereninci** [open-mmlab/mmcv#1107] opened 2021-06-17 12:49 UTC
After 2000 training iterations, I get the following error. Error and runtime config are given below. 

```
checkpoint_config = dict(interval=2000)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        #dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = '/media/mmrg/DATA/inci/RepPointsV2/work_dirs/reppoints_v2_r50_fpn_giou_1x_coco/epoch_6.pth'
workflow = [('train',2000),('val',1000)]

```
```
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/media/mmrg/DATA/inci/RepPointsV2/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/mmrg/anaconda3/envs/torch_mmdet/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/mmrg/anaconda3/envs/torch_mmdet/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/mmrg/anaconda3/envs/torch_mmdet/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 77, in val
    outputs = self.model.val_step(data_batch, **kwargs)
  File "/home/mmrg/anaconda3/envs/torch_mmdet/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 89, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
TypeError: val_step() missing 1 required positional argument: 'optimizer'
```

**Comment by zhouzaida** [comment] 2021-06-17 12:55
hi @alpereninci , please refer to #1048

**Comment by alpereninci** [comment] 2021-06-18 11:05
> hi @alpereninci , please refer to #1048

I made the changes according to #1048. I tried either adding optimizer in val_step and deleting it. Now, the code never makes validation.  To test the code, I used following configs.

```
checkpoint_config = dict(interval=50)
# yapf:disable
log_config = dict(
    interval=5,
    hooks=[
        #dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = '/media/mmrg/DATA/inci/RepPointsV2/work_dirs/reppoints_v2_r50_fpn_giou_1x_coco/epoch_6.pth'
workflow = [('train',10),('val',100)]
```

**Comment by zhouzaida** [comment] 2021-06-22 02:42
@nbei , please have a look at this

**Comment by alpereninci** [comment] 2021-06-27 12:18
> @nbei , please have a look at this

https://github.com/open-mmlab/mmdetection/issues/5382#issue-923337074

Same issue with mine. EpochBasedRunner works fine but IterBasedRunner does not make validation and so does not show a validation log.

**Comment by zhouzaida** [comment] 2021-06-30 08:00
> > @nbei , please have a look at this
> 
> [open-mmlab/mmdetection#5382 (comment)](https://github.com/open-mmlab/mmdetection/issues/5382#issue-923337074)
> 
> Same issue with mine. EpochBasedRunner works fine but IterBasedRunner does not show a validation log.

hi @alpereninci , the bug is caused by the missing after_val_iter of LoggerHook #1163 . We are resolving the bug.

**Comment by zhouzaida** [comment] 2021-08-24 12:03
closed by https://github.com/open-mmlab/mmdetection/pull/5490

**Closed by zhouzaida** 2021-08-24 12:03 UTC
