### ISSUE TITLE
bug of resume model:

### ISSUE THREAD

**Issue by luckycaicai** [open-mmlab/mmcv#1130] opened 2021-06-23 12:31 UTC
Original code:
https://github.com/open-mmlab/mmcv/blob/54ece10ffb144f572c1527b42072f6f925ff4bdf/mmcv/runner/iter_based_runner.py#L203
Fix to:
`self.meta.update(meta)`

As well as,
https://github.com/open-mmlab/mmcv/blob/54ece10ffb144f572c1527b42072f6f925ff4bdf/mmcv/runner/epoch_based_runner.py#L159

**Comment by zhouzaida** [comment] 2021-06-24 03:48
meta is the information to be saved in the checkpoint rather than self.meta

**Comment by luckycaicai** [comment] 2021-06-24 06:41
I know that, but the trouble is, you have initialized self.meta in base_runner.resume, like this:
https://github.com/open-mmlab/mmcv/blob/59ed0dddf1e3a16705f6d5df8de7d821905b3c66/mmcv/runner/base_runner.py#L362
but not do any update it after epoch/iter.

For example, when I resume model from epoch=4, iter=200, and save model after 1 epoch, after the line,
https://github.com/open-mmlab/mmcv/blob/54ece10ffb144f572c1527b42072f6f925ff4bdf/mmcv/runner/iter_based_runner.py#L203
meta is updated by self.meta, the saved information is always epoch=4, iter=200. 
It will be always the meta you initialized.

so, the following line maybe the simplest solution to fix it.
`self.meta.update(meta)`

**Comment by ailias** [comment] 2021-06-24 08:27
I think you

> I know that, but the trouble is, you have initialized self.meta in base_runner.resume, like this:
> https://github.com/open-mmlab/mmcv/blob/59ed0dddf1e3a16705f6d5df8de7d821905b3c66/mmcv/runner/base_runner.py#L362
> 
> 
> but not do any update it after epoch/iter.
> For example, when I resume model from epoch=4, iter=200, and save model after 1 epoch, after the line,
> https://github.com/open-mmlab/mmcv/blob/54ece10ffb144f572c1527b42072f6f925ff4bdf/mmcv/runner/iter_based_runner.py#L203
> 
> 
> meta is updated by self.meta, the saved information is always epoch=4, iter=200.
> It will be always the meta you initialized.
> so, the following line maybe the simplest solution to fix it.
> `self.meta.update(meta)`

I think you are right.  Actually I had trained my model to 7 epoches, but after I resume from ckpt it returned to previous 4 epoches.

**Comment by zhouzaida** [comment] 2021-06-24 09:10
@luckycaicai @ailias , thanks for your feedback, the issue is resolved by the PR #1108

**Closed** 2021-06-30 11:24 UTC
