### ISSUE TITLE
ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by Jwzzt007** [open-mmlab/mmcv#969] opened 2021-04-19 13:08 UTC
(pytorch) jwz@jwz-B450M-AORUS-ELITE:~/图片$ cd mmcv/
(pytorch) jwz@jwz-B450M-AORUS-ELITE:~/图片/mmcv$ MMCV_WITH_OPS=1 pip install -e .
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Obtaining file:///home/jwz/%E5%9B%BE%E7%89%87/mmcv
Requirement already satisfied: addict in /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages (from mmcv-full==1.3.1) (2.4.0)
Requirement already satisfied: numpy in /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages (from mmcv-full==1.3.1) (1.20.2)
Requirement already satisfied: Pillow in /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages (from mmcv-full==1.3.1) (8.2.0)
Requirement already satisfied: pyyaml in /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages (from mmcv-full==1.3.1) (5.4.1)
Requirement already satisfied: yapf in /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages (from mmcv-full==1.3.1) (0.31.0)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /home/jwz/miniconda3/envs/pytorch/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/jwz/图片/mmcv/setup.py'"'"'; __file__='"'"'/home/jwz/图片/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/jwz/图片/mmcv/
    Complete output (127 lines):
    running develop
    running egg_info
    creating mmcv_full.egg-info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    creating /home/jwz/图片/mmcv/build
    creating /home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8
    creating /home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv
    creating /home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops
    creating /home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc
    creating /home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch
    Emitting ninja build file /home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    [1/47] /usr/local/cuda-11.1/bin/nvcc --generate-dependencies-with-compile --dependency-output '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/deform_conv_cuda.o'.d -DMMCV_WITH_CUDA '-I/home/jwz/图片/mmcv/mmcv/ops/csrc' -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/jwz/miniconda3/envs/pytorch/include/python3.8 -c -c '/home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch/deform_conv_cuda.cu' -o '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/deform_conv_cuda.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/deform_conv_cuda.o
    /usr/local/cuda-11.1/bin/nvcc --generate-dependencies-with-compile --dependency-output '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/deform_conv_cuda.o'.d -DMMCV_WITH_CUDA '-I/home/jwz/图片/mmcv/mmcv/ops/csrc' -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/jwz/miniconda3/envs/pytorch/include/python3.8 -c -c '/home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch/deform_conv_cuda.cu' -o '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/deform_conv_cuda.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    /usr/include/c++/10/chrono: In substitution of ‘template<class _Rep, class _Period> template<class _Period2> using __is_harmonic = std::__bool_constant<(std::ratio<((_Period2::num / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::num, _Period::num)) * (_Period::den / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::den, _Period::den))), ((_Period2::den / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::den, _Period::den)) * (_Period::num / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::num, _Period::num)))>::den == 1)> [with _Period2 = _Period2; _Rep = _Rep; _Period = _Period]’:
    /usr/include/c++/10/chrono:473:154:   required from here
    /usr/include/c++/10/chrono:428:27: internal compiler error: 段错误
      428 |  _S_gcd(intmax_t __m, intmax_t __n) noexcept
          |                           ^~~~~~
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
    [2/47] c++ -MMD -MF '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o'.d -pthread -B /home/jwz/miniconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA '-I/home/jwz/图片/mmcv/mmcv/ops/csrc' -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/jwz/miniconda3/envs/pytorch/include/python3.8 -c -c '/home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.cpp' -o '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                     from /home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch_cpp_helper.hpp:3,
                     from /home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.cpp:4:
    /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:83: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
       83 | #pragma omp parallel for if ((end - begin) >= grain_size)
          |
    [3/47] c++ -MMD -MF '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/deform_roi_pool.o'.d -pthread -B /home/jwz/miniconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA '-I/home/jwz/图片/mmcv/mmcv/ops/csrc' -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/jwz/miniconda3/envs/pytorch/include/python3.8 -c -c '/home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch/deform_roi_pool.cpp' -o '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/deform_roi_pool.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                     from /home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch_cpp_helper.hpp:3,
                     from /home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch/deform_roi_pool.cpp:1:
    /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:83: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
       83 | #pragma omp parallel for if ((end - begin) >= grain_size)
          |
    [4/47] c++ -MMD -MF '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/roi_align.o'.d -pthread -B /home/jwz/miniconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA '-I/home/jwz/图片/mmcv/mmcv/ops/csrc' -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/jwz/miniconda3/envs/pytorch/include/python3.8 -c -c '/home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch/roi_align.cpp' -o '/home/jwz/图片/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/roi_align.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                     from /home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch_cpp_helper.hpp:3,
                     from /home/jwz/图片/mmcv/mmcv/ops/csrc/pytorch/roi_align.cpp:1:
    /home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:83: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
       83 | #pragma omp parallel for if ((end - begin) >= grain_size)
          |
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
        subprocess.run(
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jwz/图片/mmcv/setup.py", line 292, in <module>
        setup(
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
        build_ext.build_extensions(self)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/jwz/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/jwz/miniconda3/envs/pytorch/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/jwz/图片/mmcv/setup.py'"'"'; __file__='"'"'/home/jwz/图片/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by Jwzzt007** [comment] 2021-04-19 13:19
I found the solution, use gcc 9.3.0 instead of gcc 10.3.0

**Comment by zhouzaida** [comment] 2021-04-19 13:20
hi, @Jwzzt007 , if the issue is resolved, please close it. Thanks.

**Closed** 2021-04-24 15:17 UTC
