### ISSUE TITLE
undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

### ISSUE THREAD

**Issue by Candy-Crusher** [open-mmlab/mmcv#2514] opened 2022-12-27 02:40 UTC
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**Describe the Issue**
A clear and concise description of what the bug is, including what results are expected and what the real results you got.

**Reproduction**

1. What command, code, or script did you run?

```bash
python xxx.py
```

3. Did you make any modifications on the code? Did you understand what you have modified? No

**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
python -c "from mmcv.utils import collect_env; print(collect_env())"
{'sys.platform': 'linux', 'Python': '3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]', 'CUDA available': True, 'GPU 0,1,2,3,4,5,6,7': 'NVIDIA TITAN Xp', 'CUDA_HOME': '/data/envs/cuda', 'NVCC': 'Cuda compilation tools, release 11.6, V11.6.124', 'GCC': 'gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0', 'PyTorch': '1.12.1+cu116', 'PyTorch compiling details': 'PyTorch built with:\n - GCC 9.3\n - C++ Version: 201402\n - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n - OpenMP 201511 (a.k.a. OpenMP 4.5)\n - LAPACK is enabled (usually provided by MKL)\n - NNPACK is enabled\n - CPU capability usage: AVX2\n - CUDA Runtime 11.6\n - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n - CuDNN 8.3.2 (built against CUDA 11.5)\n - Magma 2.6.1\n - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n', 'TorchVision': '0.13.1+cu116', 'OpenCV': '4.5.5', 'MMCV': '1.6.2', 'MMCV Compiler': 'GCC 9.3', 'MMCV CUDA Compiler': '11.6'}
(torch_latest)

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\] 
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.
ImportError: XXX_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryForlt_policy_implENS_12MemoryFormatE

```none
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by zhouzaida** [comment] 2022-12-27 02:51
This issue is a duplicate of another solved issue, please see that issue ##2313.

**Closed by zhouzaida** 2022-12-27 02:51 UTC

**Comment by Candy-Crusher** [comment] 2022-12-27 03:09
Tried that, still got this problem. My installed versions are as followed:
mmcv-full                 1.7.0                    pypi_0    pypi                                                                                                                              
mmdet                     2.26.0                    dev_0    <develop>                                                                                                                         
mmdet3d                   1.0.0rc4                  dev_0    <develop>                                                                                                                         
mmsegmentation            0.29.1                    dev_0    <develop>

**Comment by zhouzaida** [comment] 2022-12-27 03:20
Hi, you can uninstall mmcv-full and install it with openmim.

```bash
pip install openmim
mim install mmcv-full
```

**Comment by Candy-Crusher** [comment] 2022-12-27 03:26
According to issue #2313, I've done 
pip uninstall mmcv-full -y
pip install -U openmim
mim install mmcv-full
This doesn't seem to solve my problem. And I think it may be worth mentioning that this error happened when the code tried to invoke a cpp&cu extension code.

**Comment by zhouzaida** [comment] 2022-12-27 03:31
Could you provide the log of installing mmcv-full?

**Comment by Candy-Crusher** [comment] 2022-12-27 03:33
**code**
pip uninstall mmcv-full -y
pip install -U openmim
mim install mmcv-full

**log**
Found existing installation: mmcv-full 1.6.2                                                                                                                                                   
Uninstalling mmcv-full-1.6.2:                                                                                                                                                                  
  Successfully uninstalled mmcv-full-1.6.2                                                                                                                                                     
Looking in indexes: http://mirrors.i.brainpp.cn/pypi/simple/, http://pypi.i.brainpp.cn/brain/dev/+simple                                                                                       
Requirement already satisfied: openmim in /data/envs/torch_latest/lib/python3.8/site-packages (0.3.3)                                                                                          
Requirement already satisfied: Click in /data/envs/torch_latest/lib/python3.8/site-packages (from openmim) (8.1.3)                                                                             
Requirement already satisfied: colorama in /data/envs/torch_latest/lib/python3.8/site-packages (from openmim) (0.4.4)                                                                          
Requirement already satisfied: model-index in /data/envs/torch_latest/lib/python3.8/site-packages (from openmim) (0.1.11)                                                                      
Requirement already satisfied: requests in /data/envs/torch_latest/lib/python3.8/site-packages (from openmim) (2.27.1)                                                                         
Requirement already satisfied: pandas in /data/envs/torch_latest/lib/python3.8/site-packages (from openmim) (1.4.2)                                                                            
Requirement already satisfied: pip>=19.3 in /data/envs/torch_latest/lib/python3.8/site-packages (from openmim) (21.2.4)                                                                        
Requirement already satisfied: tabulate in /data/envs/torch_latest/lib/python3.8/site-packages (from openmim) (0.8.9)                                                                          
Requirement already satisfied: rich in /data/envs/torch_latest/lib/python3.8/site-packages (from openmim) (12.6.0)                                                                             
Requirement already satisfied: ordered-set in /data/envs/torch_latest/lib/python3.8/site-packages (from model-index->openmim) (4.1.0)                                                          
Requirement already satisfied: pyyaml in /data/envs/torch_latest/lib/python3.8/site-packages (from model-index->openmim) (5.4.1)                                                               
Requirement already satisfied: markdown in /data/envs/torch_latest/lib/python3.8/site-packages (from model-index->openmim) (3.3.7)                                                             
Requirement already satisfied: importlib-metadata>=4.4 in /data/envs/torch_latest/lib/python3.8/site-packages (from markdown->model-index->openmim) (4.11.3)                                   
Requirement already satisfied: zipp>=0.5 in /data/envs/torch_latest/lib/python3.8/site-packages (from importlib-metadata>=4.4->markdown->model-index->openmim) (3.8.0)                         
Requirement already satisfied: pytz>=2020.1 in /data/envs/torch_latest/lib/python3.8/site-packages (from pandas->openmim) (2022.1)                                                             
Requirement already satisfied: python-dateutil>=2.8.1 in /data/envs/torch_latest/lib/python3.8/site-packages (from pandas->openmim) (2.8.2)                                                    
Requirement already satisfied: numpy>=1.18.5 in /data/envs/torch_latest/lib/python3.8/site-packages (from pandas->openmim) (1.19.5)                                                            
Requirement already satisfied: six>=1.5 in /data/envs/torch_latest/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->openmim) (1.15.0)                                         
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data/envs/torch_latest/lib/python3.8/site-packages (from requests->openmim) (1.26.9)                                                  
Requirement already satisfied: charset-normalizer~=2.0.0 in /data/envs/torch_latest/lib/python3.8/site-packages (from requests->openmim) (2.0.12)                                              
Requirement already satisfied: certifi>=2017.4.17 in /data/envs/torch_latest/lib/python3.8/site-packages (from requests->openmim) (2021.10.8)                                                  
Requirement already satisfied: idna<4,>=2.5 in /data/envs/torch_latest/lib/python3.8/site-packages (from requests->openmim) (3.3)                                                              
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /data/envs/torch_latest/lib/python3.8/site-packages (from rich->openmim) (2.12.0)                                                     
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /data/envs/torch_latest/lib/python3.8/site-packages (from rich->openmim) (4.4.0)                                               
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /data/envs/torch_latest/lib/python3.8/site-packages (from rich->openmim) (0.9.1)                                                   
/data/gd_products/miniconda3/envs/torch_latest/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.                                     
  warnings.warn("Setuptools is replacing distutils.")                                                                                                                                          
Looking in indexes: http://mirrors.i.brainpp.cn/pypi/simple/, http://pypi.i.brainpp.cn/brain/dev/+simple                                                                                       
Looking in links: https://download.openmmlab.com/mmcv/dist/cu116/torch1.12.0/index.html                                                                                                        
Collecting mmcv-full                                                                                                                                                                           
  Downloading https://download.openmmlab.com/mmcv/dist/cu116/torch1.12.0/mmcv_full-1.7.0-cp38-cp38-manylinux1_x86_64.whl (43.4 MB)                                                             
     |████████████████████████████████| 43.4 MB 472 kB/s                                                                                                                                       
Requirement already satisfied: Pillow in /data/envs/torch_latest/lib/python3.8/site-packages (from mmcv-full) (9.1.0)
Requirement already satisfied: packaging in /data/envs/torch_latest/lib/python3.8/site-packages (from mmcv-full) (21.3)
Requirement already satisfied: yapf in /data/envs/torch_latest/lib/python3.8/site-packages (from mmcv-full) (0.32.0)
Requirement already satisfied: numpy in /data/envs/torch_latest/lib/python3.8/site-packages (from mmcv-full) (1.19.5)
Requirement already satisfied: opencv-python>=3 in /data/envs/torch_latest/lib/python3.8/site-packages (from mmcv-full) (4.5.5.64)
Requirement already satisfied: pyyaml in /data/envs/torch_latest/lib/python3.8/site-packages (from mmcv-full) (5.4.1)
Requirement already satisfied: addict in /data/envs/torch_latest/lib/python3.8/site-packages (from mmcv-full) (2.4.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /data/envs/torch_latest/lib/python3.8/site-packages (from packaging->mmcv-full) (3.0.8)
Installing collected packages: mmcv-full
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mmdet3d 1.0.0rc4 requires mmcv-full<=1.6.0,>=1.4.8, but you have mmcv-full 1.7.0 which is incompatible.
mmsegmentation 0.29.1 requires mmcv-full<1.7.0,>=1.4.4, but you have mmcv-full 1.7.0 which is incompatible.
Successfully installed mmcv-full-1.7.0

**Comment by Candy-Crusher** [comment] 2022-12-27 03:37
> According to issue #2313, I've done pip uninstall mmcv-full -y pip install -U openmim mim install mmcv-full This doesn't seem to solve my problem. And I think it may be worth mentioning that this error happened when the code tried to invoke a cpp&cu extension code.

ImportError: /.../self_defined_cpp_code_folder/[self_defined_code_ext.cpython-38-x86_64-linux-gnu.so](http://voxel_pooling_ext.cpython-38-x86_64-linux-gnu.so/): undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

**Comment by chinalihua** [comment] 2023-03-08 07:15
Could you please solve this problem? I also encountered the same problem. cuda10.4+ pytorch1.12 environment running program mmcv error mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs

**Comment by chinalihua** [comment] 2023-03-08 07:18
> 

I have tried to reinstall mmcv from pip, mim, mim and source code, and installed mmcv1.7.0 according to the documentation, but they all reported the same error
<img width="969" alt="image" src="https://user-images.githubusercontent.com/28050413/223647050-b90488a8-3d77-4955-a0a6-4fff9efdf59f.png">

**Comment by FRAOTIAC** [comment] 2024-09-04 06:26
I encountered the same error, but after running pip install torch==1.9.1+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html, it worked for me.
