### ISSUE TITLE
Can't install mmcv-full. Reported 'Ninja: build stopped: subcommand failed'

### ISSUE THREAD

**Issue by MeteoriteWeny** [open-mmlab/mmcv#575] opened 2020-09-23 09:05 UTC
I try to install mmcv-full from 'pip install mmcv-full' and it reported 'Ninja: build stopped: subcommand failed'.  It happened again when I try to build mmcv-full from source.

Here's some information about this issue:
Platform= Window 10 Version 2004. 
Python=3.7 (virtual env build with Anaconda) , 
CUDA=10.2,
Pytorch=1.6.0

I wonder If there's any solution about it. Thank you.

By the way, the first time I tried to install mmcv-full, and I used pip, Warning: 'DEPRECATION: Could not build wheels for mmcv-full which do not use PEP 517.' happened but it can not seem to be found in this log. I don't know if it helps. 

[log_pip.txt](https://github.com/open-mmlab/mmcv/files/5266779/log_pip.txt)

**Comment by ZwwWayne** [comment] 2020-09-24 08:54
Hi @MeteoriteWeny ,
This seems to be a bug caused by the incompatibility of MSVC. Could you report more details of your environment, e.g., MSVC version?

**Comment by ZwwWayne** [comment] 2020-09-24 08:55
There are some resources might be helpful: https://github.com/facebookresearch/pytorch3d/issues/10, https://github.com/kezewang/apex/commit/929eb973d2e242d08ad81efc78212c4709659087, and https://www.gitmemory.com/issue/NVIDIA/apex/839/647054367. We will also check the code to make it more robust on Windows, but this might take some time.

**Comment by MeteoriteWeny** [comment] 2020-09-24 09:33
> Hi @MeteoriteWeny ,
> This seems to be a bug caused by the incompatibility of MSVC. Could you report more details of your environment, e.g., MSVC version?

Thank you for your help. Well, I have installed the Visual Studio 2017 and MSVC 2015 Build Tools. I installed the MSVC 2015 for installing the COCO API, and no error reported. I don't know if  it caused incompatibility.  Maybe I will try again with the MSVC 2015 uninstalled.

**Comment by wangruohui** [comment] 2020-09-27 09:30
The problem seems lies at pytorch side and require some modification of pytorch's C code to make compilation complete. A little bit ugly but I haven't found better solutions yet. 

Here is a precompiled version with the same environment as yours except my VS is of version 2019 ([But binary files from 2015 to 2019 should be compatible](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019)).

[mmcv_full-1.1.3-cp37-cp37m-win_amd64.whl.zip](https://github.com/open-mmlab/mmcv/files/5288027/mmcv_full-1.1.3-cp37-cp37m-win_amd64.whl.zip)

You can have a test on it.

**Comment by MeteoriteWeny** [comment] 2020-09-27 09:57
> The problem seems lies at pytorch side and require some modification of pytorch's C code to make compilation complete. A little bit ugly but I haven't found better solutions yet.
> 
> Here is a precompiled version with the same environment as yours except my VS is of version 2019 ([But binary files from 2015 to 2019 should be compatible](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019)).
> 
> [mmcv_full-1.1.3-cp37-cp37m-win_amd64.whl.zip](https://github.com/open-mmlab/mmcv/files/5288027/mmcv_full-1.1.3-cp37-cp37m-win_amd64.whl.zip)
> 
> You can have a test on it.

Thank you for offering help. I installed the mmcv-full successfully using your precompiled whl file.  

By the way, I have tried to modify the pytorch's code as you mentioned, but the method for pytorch 1.4 can not apply in pytorch 1.6. I hope this incompatibility in pip installation can be fixed later.

**Comment by wangruohui** [comment] 2020-09-27 14:24
> The problem seems lies at pytorch side and require some modification of pytorch's C code to make compilation complete. A little bit ugly but I haven't found better solutions yet.
> Here is a precompiled version with the same environment as yours except my VS is of version 2019 (But binary files from 2015 to 2019 should be compatible).
> mmcv_full-1.1.3-cp37-cp37m-win_amd64.whl.zip
> You can have a test on it.
> 
> Thank you for offering help. I installed the mmcv-full successfully using your precompiled whl file.
> By the way, I have tried to modify the pytorch's code as you mentioned, but the method for pytorch 1.4 can not apply in pytorch 1.6. I hope this incompatibility in pip installation can be fixed later.

Actually what I did on pytorch 1.6.0 is similar with point 1 in the referenced issue, i.e. change `CONSTEXPR_EXCEPT_WIN_CUDA` to `const` at lines reporting error. 
If you look deeper at `torch/include/c10/Macros.h`, where `CONSTEXPR_EXCEPT_WIN_CUDA` is defined to empty, which causes the error. 
I found a [fix](https://github.com/pytorch/pytorch/pull/43380) is already merged into pytorch's master branch, may be included in next release.

**Closed** 2020-10-14 07:47 UTC
Labels: windows
